spring.application.name=catalog-service

server.port=8080

openlibrary.api.base-url=https://openlibrary.org
openlibrary.api.covers-url=https://covers.openlibrary.org/b

logging.level.com.example.catalog_service=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
