apiVersion: v1
kind: ConfigMap
metadata:
  name: biblio-config
  namespace: biblio
data:
  # Keycloak Configuration
  KEYCLOAK_ISSUER_URI: "http://keycloak-service:8080/realms/biblio"
  KEYCLOAK_JWK_SET_URI: "http://keycloak-service:8080/realms/biblio/protocol/openid-connect/certs"
  KEYCLOAK_SERVER_URL: "http://keycloak-service:8080"

  # Database Hosts
  USER_DB_HOST: "user-db-service"
  COMMENT_DB_HOST: "comment-db-service"
  FRONTEND_DB_HOST: "frontend-db-service"

  # Database Ports
  DB_PORT: "5432"

  # Database Names
  USER_DB_NAME: "userdb"
  COMMENT_DB_NAME: "commentdb"
  FRONTEND_DB_NAME: "biblio-kubernetes"

  # Open Library API
  OPENLIBRARY_API_BASE_URL: "https://openlibrary.org"
  OPENLIBRARY_API_COVERS_URL: "https://covers.openlibrary.org/b"

  # Prometheus
  PROMETHEUS_HOST: "prometheus"
  PROMETHEUS_PORT: "9090"
